### ISSUE TITLE
nix-search-pretty

### ISSUE THREAD

**Issue by DieracDelta** [dramforever/nix-dram#2]
How do I get nix-search-pretty working? I've got the package from this flake installed but it looks I also need to apply a patch to nixpkgs. Can you provide an example of how to do this from a flake?

**Comment by dramforever** [comment]
I noticed that I forgot to include this in the readme. Assuming you got `nix` and `nix-search-pretty` from this flake you should be able to use this bash function as `nix-search`.

```bash
nix-search() {
    nix search --json "$@" | nix-search-pretty
}
```

**Comment by dramforever** [comment]
I've added `nix-search` to this flake in 88412acadc4ba330c50ab9b436e13587dce6a6a2. It should work out of the box with no changes to nixpkgs.

**Comment by DieracDelta** [comment]
This is super helpful, thanks! I ended up applying the patch to nix manually. Should have looked closer at this flake's outputs.

**Comment by dramforever** [comment]
Applying the patch manually is also a good way to use this repository, I'd say
