### ISSUE TITLE
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'

### ISSUE THREAD

**Issue by montchr** [dramforever/nix-dram#21]
As a new user, I am unable to test `nix-dram` with the command suggested in the README:

```console
$ nix run github:dramforever/nix-dram -- --version
warning: Using saved setting for 'extra-substituters = https://dram.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = dram.cachix.org-1:baoy1SXpwYdKbqdTbfKGTKauDDeDlHhUpC+QuuILEMY=' from ~/.local/share/nix/trusted-settings.json.
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'
```

Edit: in case it helps:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.05 (Quokka), 22.05.20220809.490f617`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"home-manager, nixos-22.05"`
 - channels(seadoom): `"home-manager"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

**Comment by dramforever** [comment]
Should be fixed now, though I didn't have time to try it out for now. Let me know if it's still broken.

**Comment by montchr** [comment]
Confirmed fixed, thanks!
