### ISSUE TITLE
nix flake info -> nix flake metadata

### ISSUE THREAD

**Issue by zseri** [dramforever/nix-dram#4]
please update `flake.lock` to include https://github.com/NixOS/nixpkgs/pull/116807, latest `nixos-unstable` probably suffices (e.g. `nix flake update` maybe with `--recreate-lock-file]`).

**Comment by dramforever** [comment]
Noted.

You can also try using the overlay, though it probably means needing to build it yourself.

**Comment by dramforever** [comment]
It's updated and should be good
